Repository acasi-ctf/ctf, pull requests merged in 2021-04, with the labels that each got.

#42 routingUI-update
  ui/src/App.css
  ui/src/App.js
  ui/src/Menu.js
  ui/src/Page/ChallengeSet1.css
  ui/src/Page/ChallengeSet1.js
  ui/src/Page/ChallengeSet1Data.js
  ui/src/Page/Home.css
  ui/src/Page/Home.js
  ui/src/Page/LeaderBoard.css
  ui/src/Page/LeaderBoard.js
  ui/src/Terminal.css
  ui/src/Terminal.tsx
  ui/src/components/AppBar.js
  ui/src/components/Menu.css
  ui/src/components/Menu.js
  ui/src/components/MenuBarData.js
  ui/src/index.css
  ui/src/index.tsx
  ui/src/reportWebVitals.ts
Labels: Extra Large

#33 Challenge file format + Basic Frontend API
  .dockerignore
  .github/linters/.python-black
  .github/workflows/super-linter.yaml
  .gitignore
  Makefile
  Pipfile
  Pipfile.lock
  challenges/base/challenge.schema.json
  challenges/base/provisioners/kubernetes.schema.json
  challenges/example/challenge-set.json
  challenges/example/challenge.json
  challenges/example/challenges/basic-env-example/challenge.json
  challenges/example/challenges/basic-env-example/docs/Hello1.md
  challenges/example/challenges/basic-env-example/docs/Hello2.md
  challenges/example/challenges/basic-env-example/docs/Hello3.md
  challenges/example/challenges/basic-env-example/kubernetes.json
  challenges/schemas/challenge-set.schema.json
  challenges/schemas/challenge.schema.json
  challenges/schemas/provisioners/kubernetes.schema.json
  challenges/schemas/schemas.go
  deploy/base/ui.yaml
  frontend/__init__.py
  frontend/api.yaml
  frontend/app.py
  frontend/extensions.py
  frontend/main.py
  frontend/migrations/alembic.ini
  frontend/migrations/env.py
  frontend/migrations/script.py.mako
  frontend/migrations/versions/5213f9e65a8c_add_documentation_table_and_minor_.py
  frontend/migrations/versions/6e85efd406c7_initial_migrations.py
  frontend/model/challenges.py
  frontend/routes/__init__.py
  frontend/routes/api/__init__.py
  frontend/routes/api/admin_challenges.py
  frontend/routes/api/challenges.py
  frontend/settings.py
  frontend/web/main.py
  go.mod
  go.sum
  images/frontend/Dockerfile
  images/frontend/app-uwsgi.ini
  images/frontend/entrypoint.sh
  images/frontend/install-nginx-debian.sh
  images/frontend/nginx.conf
  images/frontend/start.sh
  images/frontend/supervisord-debian.conf
  images/frontend/uwsgi-nginx-entrypoint.sh
  images/frontend/uwsgi.ini
  images/ui/Dockerfile
  pkg/challenges/validator/validator.go
  pkg/challenges/validator/validator_challenge_set_test.go
  pkg/challenges/validator/validator_challenge_test.go
  pkg/challenges/validator/validator_utils_test.go
  pkg/ctfoperator/model/environment_test.go
Labels: Extra Large

#43 Integrate with Auth0.
  frontend/migrations/env.py
  ui/package-lock.json
  ui/package.json
  ui/src/App.js
  ui/src/components/AppBar.js
  ui/src/components/AppBarActions.js
  ui/src/components/Button.js
  ui/src/index.tsx
Labels: Medium

#45 Submenu2
  ui/src/App.js
  ui/src/Page/ChallengeSet1.css
  ui/src/Page/Home.css
  ui/src/components/Menu.css
  ui/src/components/Menu.js
  ui/src/components/MenuBarData.js
  ui/src/components/SubMenu.css
  ui/src/components/SubMenu.js
Labels: Medium

#47 Add GitHub Action for UI Build
  .github/workflows/ui-build.yaml
Labels: Extra Small

#53 Last chance
  challenges/Challenge-Set-1/Docs/1-Cryptography.md
  challenges/Challenge-Set-1/Docs/Caesar-cipher.md
  challenges/Challenge-Set-1/Docs/Letter-to-Number.md
  challenges/Challenge-Set-1/Docs/Mixed-Challenge-1.md
  challenges/Challenge-Set-1/Docs/Morse_code.md
  challenges/Challenge-Set-1/Docs/Reverse.md
Labels: Medium, small

#54 added cipher python files to repo
  .github/workflows/super-linter.yaml
  Makefile
  challenges/Challenge-Set-1/Challenges/Cipher-challenge/Caesar-cipher.py
  challenges/Challenge-Set-1/Challenges/Cipher-challenge/Letter-to-Number.py
  challenges/Challenge-Set-1/Challenges/Cipher-challenge/Mixed-Challenge-1.py
  challenges/Challenge-Set-1/Challenges/Cipher-challenge/Morse_code.py
  challenges/Challenge-Set-1/Challenges/Cipher-challenge/Reverse.py
Labels: Large, small

#57 Sprint 2 + Retro Summary
  .github/linters/.markdown-lint.yml
  README.md
  frontend/__init__.py
  frontend/api.yaml
  frontend/app.py
  frontend/extensions.py
  frontend/main.py
  frontend/model/challenges.py
  frontend/routes/__init__.py
  frontend/routes/api/__init__.py
  frontend/routes/api/admin_challenges.py
  frontend/routes/api/challenges.py
  frontend/settings.py
  retros/Sprint2_RetroSummary.md
Labels: Large

#58 Add sprint 2 demo link
  README.md
Labels: Extra Small

#59 Add the Frontend API deployment
  .github/workflows/super-linter.yaml
  Makefile
  deploy/base/frontend.yaml
  deploy/base/ingress.yaml
  deploy/base/kustomization.yaml
  deploy/base/networkpolicy.yaml
  deploy/dev/kustomization.yaml
  frontend/settings.py
Labels: Medium

#60 Fix Auth0 logout for non-default URLs.
  ui/src/components/AppBarActions.js
Labels: Extra Small

#61 Improvements to the app layout.
  ui/package-lock.json
  ui/package.json
  ui/src/App.css
  ui/src/App.js
  ui/src/Terminal.css
  ui/src/Terminal.tsx
  ui/src/components/Terminal.css
  ui/src/components/Terminal.tsx
  ui/src/pageLayout.js
Labels: Medium

#63 Add terminal resize support
  images/ui/Dockerfile
  pb/common.pb.go
  pb/ctfoperator.pb.go
  pb/ctfoperator_internal.pb.go
  pb/termproxy.pb.go
  pkg/ctfoperator/environment/lookup/service.go
  pkg/termproxy/service/service.go
  proto/termproxy.proto
  ui/package-lock.json
  ui/package.json
  ui/public/index.html
  ui/src/components/Terminal.tsx
  ui/src/generated/common_pb.js
  ui/src/generated/termproxy_pb.d.ts
  ui/src/generated/termproxy_pb.js
Labels: Extra Large

#65 Update Caesar-cipher.md
  challenges/Challenge-Set-1/Docs/Caesar-cipher.md
Labels: Extra Small

#66 Update Letter-to-Number.md
  challenges/Challenge-Set-1/Docs/Letter-to-Number.md
Labels: Extra Small

#67 Update Mixed-Challenge-1.md
  challenges/Challenge-Set-1/Docs/Mixed-Challenge-1.md
Labels: Extra Small

#70 Update Reverse.md
  challenges/Challenge-Set-1/Docs/Reverse.md
Labels: Extra Small

#71 Updating morse code documentation. Reformatting last example.
  challenges/Challenge-Set-1/Docs/Morse_code.md
Labels: Extra Small

#72 Updatable banner
  ui/.env
  ui/package.json
  ui/src/App.js
  ui/src/Page/ChallengeSet1.css
  ui/src/Page/ChallengeSet1.js
  ui/src/Page/ChallengeSet1Data.js
  ui/src/Page/Selection.css
  ui/src/Page/Selection.js
  ui/src/Page/SelectionData.js
  ui/src/components/AppBar.js
  ui/src/components/Menu.js
  ui/src/components/MenuBarData.js
  ui/src/components/SubMenu.js
  ui/src/components/Terminal.css
Labels: Large

#77 Editing cipher challenges
  challenges/Challenge-Set-1/Challenges/Cipher-challenge/Caesar-cipher.py
  challenges/Challenge-Set-1/Challenges/Cipher-challenge/Letter-to-Number.py
  challenges/Challenge-Set-1/Challenges/Cipher-challenge/Mixed-Challenge-1.py
  challenges/Challenge-Set-1/Challenges/Cipher-challenge/Morse_code.py
  challenges/Challenge-Set-1/Challenges/Cipher-challenge/Reverse.py
Labels: small

#75 Documentation for WebPage Struct
  challenges/Challenge-Set-1/DirTrav-Challenge/DirTrav.md
  challenges/Challenge-Set-1/DirTrav-Challenge/DirTravDescription.md
  challenges/Challenge-Set-1/WebStruct-Challenge/BrowserTools.md
  challenges/Challenge-Set-1/WebStruct-Challenge/CSS.md
  challenges/Challenge-Set-1/WebStruct-Challenge/HTML.md
  challenges/Challenge-Set-1/WebStruct-Challenge/PHP.md
  challenges/Challenge-Set-1/WebStruct-Challenge/WebStructureDescript.md
Labels: Medium, documentation

#80 Dynamic UI
  frontend/routes/api/user_environments.py
  images/penimage/Dockerfile
  ui/package.json
  ui/src/App.js
  ui/src/Page/ChallengeSet1.js
  ui/src/Page/ChallengeSet1Data.js
  ui/src/Page/ComprehensiveChallenge.js
  ui/src/Page/ComprehensiveChallengeData.js
  ui/src/Page/DirectoryTraversalData.js
  ui/src/Page/Home.js
  ui/src/Page/LetterToNumber.js
  ui/src/Page/LetterToNumberData.js
  ui/src/Page/MorseCode.js
  ui/src/Page/MorseCodeData.js
  ui/src/Page/ReverseCipher.js
  ui/src/Page/ReverseCipherData.js
  ui/src/challenges/ciphers/challenges/comprehensive-challenge/docs/1-Cryptography.md
  ui/src/challenges/ciphers/challenges/reverse-cipher/docs/1-Cryptography.md
  ui/src/components/Spinner.jsx
  ui/src/components/Terminal.tsx
  ui/src/pages/CaeserCipher.js
  ui/src/pages/ChallengeSet1.css
  ui/src/pages/ChallengeSet1Data.js
  ui/src/pages/ChallengeSetPage.js
  ui/src/pages/ComprehensiveChallenge.js
  ui/src/pages/ComprehensiveChallengeData.js
  ui/src/pages/DirectoryTraversal.js
  ui/src/pages/DirectoryTraversalData.js
  ui/src/pages/EnvironmentPage.js
  ui/src/pages/Home.css
  ui/src/pages/Home.js
  ui/src/pages/LeaderBoard.css
  ui/src/pages/LeaderBoard.js
  ui/src/pages/LetterToNumber.js
  ui/src/pages/LetterToNumberData.js
  ui/src/pages/MorseCode.js
  ui/src/pages/MorseCodeData.js
  ui/src/pages/ReverseCipher.js
  ui/src/pages/ReverseCipherData.js
  ui/src/pages/Selection.css
  ui/src/pages/Selection.js
  ui/src/pages/SelectionData.js
  ui/src/pages/WebStructure.js
  ui/src/pages/WebStructureData.js
  ui/src/pages/error-pages/genericErrorPage.jsx
  ui/src/pages/error-pages/userNotAuthorized.jsx
  ui/src/useFetchAuth.js
Labels: Extra Large

#82 Operator tests + initial coverage reporting
  .github/workflows/go-test.yaml
  .github/workflows/operator-build-test.yaml
  .github/workflows/super-linter.yaml
  .github/workflows/ui-build.yaml
  operator/build.gradle.kts
  operator/src/main/kotlin/org/acasictf/ctf/operator/abstractions/PersistenceLayer.kt
  operator/src/main/kotlin/org/acasictf/ctf/operator/constants.kt
  operator/src/main/kotlin/org/acasictf/ctf/operator/main.kt
  operator/src/main/kotlin/org/acasictf/ctf/operator/model/Challenge.kt
  operator/src/main/kotlin/org/acasictf/ctf/operator/model/ChallengeSet.kt
  operator/src/main/kotlin/org/acasictf/ctf/operator/model/Kubernetes.kt
  operator/src/main/kotlin/org/acasictf/ctf/operator/persistence/ChallengeTemplate.kt
  operator/src/main/kotlin/org/acasictf/ctf/operator/persistence/ChallengeTemplateFile.kt
  operator/src/main/kotlin/org/acasictf/ctf/operator/persistence/EnvironmentDao.kt
  operator/src/main/kotlin/org/acasictf/ctf/operator/persistence/PersistenceLayerImpl.kt
  operator/src/main/kotlin/org/acasictf/ctf/operator/persistence/ZipChallengeTemplate.kt
  operator/src/main/kotlin/org/acasictf/ctf/operator/provisioner/KubernetesProvisioner.kt
  operator/src/main/kotlin/org/acasictf/ctf/operator/provisioner/Provisioner.kt
  operator/src/main/kotlin/org/acasictf/ctf/operator/service/LookupService.kt
  operator/src/main/kotlin/org/acasictf/ctf/operator/service/ProvisioningService.kt
  operator/src/main/kotlin/org/acasictf/ctf/operator/utils.kt
  operator/src/test/kotlin/org/acasictf/ctf/operator/provisioner/FakeChallengeTemplate.kt
  operator/src/test/kotlin/org/acasictf/ctf/operator/provisioner/KubernetesProvisionerTest.kt
  operator/src/test/kotlin/org/acasictf/ctf/operator/service/FakePersistenceLayer.kt
  operator/src/test/kotlin/org/acasictf/ctf/operator/service/ProvisioningServiceTest.kt
  operator/src/test/kotlin/org/acasictf/ctf/operator/utils.kt
  operator/src/test/resources/655081bb-aa0b-43c1-a099-f1c04177ba0c/challenge-set.json
  operator/src/test/resources/655081bb-aa0b-43c1-a099-f1c04177ba0c/challenges/basic-env-example/challenge.json
  operator/src/test/resources/655081bb-aa0b-43c1-a099-f1c04177ba0c/challenges/basic-env-example/kubernetes.json
  operator/src/test/resources/655081bb-aa0b-43c1-a099-f1c04177ba0c/challenges/dvwa-example/challenge.json
  operator/src/test/resources/655081bb-aa0b-43c1-a099-f1c04177ba0c/challenges/dvwa-example/dvwa.yaml
  operator/src/test/resources/655081bb-aa0b-43c1-a099-f1c04177ba0c/challenges/dvwa-example/kubernetes.json
Labels: Extra Large

#84 Updating sprint docs
  README.md
Labels: Extra Small

#83 More Operator testing
  operator/build.gradle.kts
  operator/gradle/wrapper/gradle-wrapper.properties
  operator/src/main/kotlin/org/acasictf/ctf/operator/main.kt
  operator/src/main/kotlin/org/acasictf/ctf/operator/persistence/EnvironmentDao.kt
  operator/src/main/kotlin/org/acasictf/ctf/operator/persistence/ProxyPublicKey.kt
  operator/src/main/kotlin/org/acasictf/ctf/operator/provisioner/KubernetesProvisioner.kt
  operator/src/main/kotlin/org/acasictf/ctf/operator/service/LookupService.kt
  operator/src/main/kotlin/org/acasictf/ctf/operator/service/ProvisioningService.kt
  operator/src/main/kotlin/org/acasictf/ctf/operator/utils.kt
  operator/src/test/kotlin/org/acasictf/ctf/operator/TestChallengeId.kt
  operator/src/test/kotlin/org/acasictf/ctf/operator/model/ModelTest.kt
  operator/src/test/kotlin/org/acasictf/ctf/operator/persistence/ChallengeTemplateTest.kt
  operator/src/test/kotlin/org/acasictf/ctf/operator/persistence/EnvironmentDaoTest.kt
  operator/src/test/kotlin/org/acasictf/ctf/operator/persistence/ProxyPublicKeyTest.kt
  operator/src/test/kotlin/org/acasictf/ctf/operator/persistence/ResourceChallengeTemplate.kt
  operator/src/test/kotlin/org/acasictf/ctf/operator/persistence/StringChallengeTemplateFile.kt
  operator/src/test/kotlin/org/acasictf/ctf/operator/provisioner/FakeChallengeTemplate.kt
  operator/src/test/kotlin/org/acasictf/ctf/operator/provisioner/KubernetesProvisionerTest.kt
  operator/src/test/kotlin/org/acasictf/ctf/operator/service/FakePersistenceLayer.kt
  operator/src/test/kotlin/org/acasictf/ctf/operator/service/LookupServiceTest.kt
  operator/src/test/kotlin/org/acasictf/ctf/operator/service/ProvisioningServiceTest.kt
  operator/src/test/kotlin/org/acasictf/ctf/operator/testutil/assert.kt
  operator/src/test/kotlin/org/acasictf/ctf/operator/testutil/util.kt
  operator/src/test/resources/README.md
Labels: Extra Large, small

#85 Finalize sprint 3 documentation
  README.md
  operator/src/main/kotlin/org/acasictf/ctf/operator/service/ProvisioningService.kt
  retros/Sprint3_RetroSummary.md
Labels: Medium
