Repository acasi-ctf/ctf, pull requests merged in 2021-11, with the labels that each got.

#152 Sprint6 java games
  challenges/games/challenge-set.json
  challenges/games/challenges/noughts/challenge.json
  challenges/games/challenges/noughts/docs/Noughts.md
  challenges/games/challenges/noughts/kubernetes.json
  challenges/games/challenges/noughts/pod.yaml
  challenges/games/challenges/noughts/src/Noughts.java
  challenges/games/challenges/prize/challenge.json
  challenges/games/challenges/prize/docs/DoorGame.md
  challenges/games/challenges/prize/kubernetes.json
  challenges/games/challenges/prize/pod.yaml
  challenges/games/challenges/prize/src/Prize.java
  challenges/games/challenges/rock-paper-scissors/challenge.json
  challenges/games/challenges/rock-paper-scissors/docs/RockPaperScissors.md
  challenges/games/challenges/rock-paper-scissors/kubernetes.json
  challenges/games/challenges/rock-paper-scissors/pod.yaml
  challenges/games/challenges/rock-paper-scissors/src/RockPaperScissors.java
  challenges/games/challenges/seven-up/challenge.json
  challenges/games/challenges/seven-up/docs/SevenUp.md
  challenges/games/challenges/seven-up/kubernetes.json
  challenges/games/challenges/seven-up/pod.yaml
  challenges/games/challenges/seven-up/src/SevenUp.java
  challenges/games/challenges/yahtzee/src/Dice.java
  challenges/games/challenges/yahtzee/src/DiceGroup.java
  challenges/games/challenges/yahtzee/src/Prompt.java
  challenges/games/challenges/yahtzee/src/Yahtzee.java
  challenges/games/challenges/yahtzee/src/YahtzeePlayer.java
  challenges/games/challenges/yahtzee/src/YahtzeeScoreCard.java
  images/challenges/games/noughts/Dockerfile
  images/challenges/games/prize/Dockerfile
  images/challenges/games/rock-paper-scissors/Dockerfile
  images/challenges/games/seven-up/Dockerfile
  ui/package-lock.json
Labels: 3 story pts, challenges

#153 Sprint6 top challenges
  .gitignore
  frontend/migrations/versions/cd0b94f49e8a_add_user_challenges_table.py
  frontend/model/challenges.py
  frontend/routes/api/challenges.py
  frontend/routes/api/user_environments.py
Labels: 3 story pts

#160 Update OpenAPI spec to add new top challenges API.
  frontend/api.yaml
Labels: 1 story pt

#163 Sprint5 kali tools
  challenges/kali/challenge-set.json
  challenges/kali/challenges/Tools.md
  challenges/kali/challenges/binwalk/challenge.json
  challenges/kali/challenges/binwalk/docs/BinwalkDocument.md
  challenges/kali/challenges/binwalk/kubernetes.json
  challenges/kali/challenges/binwalk/template.yaml
  challenges/kali/challenges/strings/challenge.json
  challenges/kali/challenges/strings/docs/StringsDocument.md
  challenges/kali/challenges/strings/kubernetes.json
  challenges/kali/challenges/strings/src/lock.cpp
  challenges/kali/challenges/strings/template.yaml
  images/challenges/kali/binwalk/Dockerfile
  images/challenges/kali/strings/Dockerfile
Labels: 3 story pts

#165 Upsert database instead of delete and reinsert.
  frontend/challenges/model_reconciler.py
  frontend/routes/api/admin_challenges.py
Labels: 1 story pt

#167 Sprint6 richard
  ui/package-lock.json
  ui/package.json
  ui/src/App.js
  ui/src/components/AppBar.js
  ui/src/components/AppBarActions.js
  ui/src/components/Menu.js
  ui/src/components/SubMenu.js
  ui/src/pages/ChallengePage.js
  ui/src/style/App.css
  ui/src/style/ChallengePage.css
  ui/src/style/Terminal.css
Labels: 3 story pts

#169 Rebranding from CTF to CyberLiteracyForAll
  challenges/ciphers/challenges/caesar-cipher/challenge.json
  challenges/ciphers/challenges/caesar-cipher/docs/Terminal_Use.md
  challenges/ciphers/challenges/comprehensive-challenge/challenge.json
  challenges/ciphers/challenges/comprehensive-challenge/docs/Terminal_Use.md
  challenges/ciphers/challenges/letter-to-number/challenge.json
  challenges/ciphers/challenges/letter-to-number/docs/Terminal_Use.md
  challenges/ciphers/challenges/morse-code/challenge.json
  challenges/ciphers/challenges/morse-code/docs/Terminal_Use.md
  challenges/ciphers/challenges/reverse-cipher/challenge.json
  challenges/ciphers/challenges/reverse-cipher/docs/Terminal_Use.md
  ui/public/index.html
  ui/public/logo-dark.svg
  ui/src/App.js
  ui/src/challenges/ciphers/challenges/caesar-cipher/docs/1-Cryptography.md
  ui/src/challenges/ciphers/challenges/caesar-cipher/docs/Caesar-cipher.md
  ui/src/challenges/ciphers/challenges/comprehensive-challenge/docs/1-Cryptography.md
  ui/src/challenges/ciphers/challenges/comprehensive-challenge/docs/Mixed-Challenge-1.md
  ui/src/challenges/ciphers/challenges/letter-to-number/docs/1-Cryptography.md
  ui/src/challenges/ciphers/challenges/letter-to-number/docs/Letter-to-Number.md
  ui/src/challenges/ciphers/challenges/morse-code/docs/1-Cryptography.md
  ui/src/challenges/ciphers/challenges/morse-code/docs/Morse_code.md
  ui/src/challenges/ciphers/challenges/reverse-cipher/docs/1-Cryptography.md
  ui/src/challenges/ciphers/challenges/reverse-cipher/docs/Reverse.md
  ui/src/challenges/web-based/challenges/directory-traversal/docs/DirTrav.md
  ui/src/challenges/web-based/challenges/directory-traversal/docs/DirTravDescription.md
  ui/src/challenges/web-based/challenges/web-structure/docs/BrowserTools.md
  ui/src/challenges/web-based/challenges/web-structure/docs/CSS.md
  ui/src/challenges/web-based/challenges/web-structure/docs/HTML.md
  ui/src/challenges/web-based/challenges/web-structure/docs/PHP.md
  ui/src/challenges/web-based/challenges/web-structure/docs/WebStructureDescript.md
  ui/src/dynamic_pages/App.css
  ui/src/dynamic_pages/App.js
  ui/src/dynamic_pages/Pages/ChallengePage.jsx
  ui/src/dynamic_pages/Pages/ChallengeSets.jsx
  ui/src/pageLayout.js
  ui/src/pages/Home.js
  ui/src/pages/Selection.js
  ui/src/pages/SelectionData.js
  ui/src/pages/error-pages/ChallengeSetsNotFound.jsx
  ui/src/pages/error-pages/preLoginPage.jsx
  ui/src/style/App.css
Labels: 2 story pt

#172 Sprint6 kali
  challenges/kali/challenge-set.json
  challenges/pentesting/DockerNotes.md
  challenges/pentesting/HOW_TO.md
  challenges/pentesting/challenge-set.json
  challenges/pentesting/challenges/Tools.md
  challenges/pentesting/challenges/binwalk/challenge.json
  challenges/pentesting/challenges/binwalk/docs/BinwalkDocument.md
  challenges/pentesting/challenges/binwalk/kubernetes.json
  challenges/pentesting/challenges/binwalk/template.yaml
  challenges/pentesting/challenges/hash-identifier/challenge.json
  challenges/pentesting/challenges/hash-identifier/docs/HashIdentDocumentation.md
  challenges/pentesting/challenges/hash-identifier/kubernetes.json
  challenges/pentesting/challenges/hash-identifier/src/Plain
  challenges/pentesting/challenges/hash-identifier/src/password1
  challenges/pentesting/challenges/hash-identifier/src/password2
  challenges/pentesting/challenges/hash-identifier/src/password3
  challenges/pentesting/challenges/hash-identifier/src/password4
  challenges/pentesting/challenges/hash-identifier/template.yaml
  challenges/pentesting/challenges/hashcat/challenge.json
  challenges/pentesting/challenges/hashcat/docs/HashcatDocumentation.md
  challenges/pentesting/challenges/hashcat/kubernetes.json
  challenges/pentesting/challenges/hashcat/src/hashed-password
  challenges/pentesting/challenges/hashcat/template.yaml
  challenges/pentesting/challenges/strings/challenge.json
  challenges/pentesting/challenges/strings/docs/StringsDocument.md
  challenges/pentesting/challenges/strings/kubernetes.json
  challenges/pentesting/challenges/strings/src/lock.cpp
  challenges/pentesting/challenges/strings/template.yaml
  images/challenges/pentesting/binwalk/Dockerfile
  images/challenges/pentesting/hash-identifier/Dockerfile
  images/challenges/pentesting/hashcat/Dockerfile
  images/challenges/pentesting/strings/Dockerfile
Labels: 3 story pts

#171 Sprint 6 report
  sprint-reports/Sprint 6.md
Labels: 1 story pt

#176 Backend support for flags
  challenges/pentesting/challenges/strings/challenge.json
  challenges/schemas/challenge.schema.json
  frontend/api.yaml
  frontend/challenges/model_reconciler.py
  frontend/migrations/versions/577e3355a0e3_add_challenge_features_and_flags.py
  frontend/migrations/versions/b8d0f7f85bdd_add_environment_id_to_user_challenges.py
  frontend/model/challenges.py
  frontend/routes/api/challenges.py
  frontend/routes/api/user_environments.py
  operator/src/test/kotlin/org/acasictf/ctf/operator/model/ModelTest.kt
  ui/package-lock.json
  ui/package.json
  ui/src/App.js
  ui/src/components/AppBarActions.js
  ui/src/components/Terminal.tsx
  ui/src/pages/ChallengePage.js
  ui/src/pages/StartChallengePage.js
  ui/src/state.js
Labels: 3 story pts

#187 Add and implement database + API for completed challenges and leaderboard.
  frontend/api.yaml
  frontend/migrations/versions/74f03c8be8dd_add_completed_challenges.py
  frontend/model/challenges.py
  frontend/routes/api/challenges.py
  frontend/routes/api/user_environments.py
Labels: 1 story pt

#188 Implement basic Kubernetes environment purger.
  codecov.yml
  operator/src/main/kotlin/org/acasictf/ctf/operator/main.kt
  operator/src/main/kotlin/org/acasictf/ctf/operator/provisioner/Purger.kt
  operator/src/main/kotlin/org/acasictf/ctf/operator/provisioner/kubernetes/KubernetesProvisioner.kt
  operator/src/main/kotlin/org/acasictf/ctf/operator/provisioner/kubernetes/KubernetesPurger.kt
  operator/src/test/kotlin/org/acasictf/ctf/operator/provisioner/kubernetes/KubernetesPurgerTest.kt
Labels: 1 story pt

#190 Fix terminal size not being correct unless first resized.
  ui/src/components/Terminal.tsx
Labels: bug, 1 story pt

#192 Add admin upload challenge set page.
  challenges/pentesting/challenge-set.json
  ui/src/App.js
  ui/src/components/Menu.js
  ui/src/components/MenuBarData.js
  ui/src/pages/admin/UploadChallengeSet.js
Labels: 2 story pt

#202 Implement trending challenges API.
  frontend/routes/api/challenges.py
Labels: 1 story pt

#203 Initial clean up of games challenge set.
  Makefile
  challenges/games/challenges/noughts/src/Noughts.java
  challenges/games/challenges/prize/src/Prize.java
  challenges/games/challenges/rock-paper-scissors/src/RockPaperScissors.java
  challenges/games/challenges/seven-up/src/SevenUp.java
Labels: 1 story pt

#201 Sprint7 update documentation in various places on the site
  challenges/ciphers/challenges/caesar-cipher/challenge.json
  challenges/ciphers/challenges/caesar-cipher/docs/Caesar-cipher.md
  challenges/ciphers/challenges/comprehensive-challenge/challenge.json
  challenges/ciphers/challenges/comprehensive-challenge/code/Comprehensive-Challenge.py
  challenges/ciphers/challenges/comprehensive-challenge/docs/1-Cryptography.md
  challenges/ciphers/challenges/comprehensive-challenge/docs/Mixed-Challenge.md
  challenges/ciphers/challenges/letter-to-number/challenge.json
  challenges/ciphers/challenges/letter-to-number/docs/1-Cryptography.md
  challenges/ciphers/challenges/letter-to-number/docs/Letter-to-Number.md
  challenges/ciphers/challenges/morse-code/docs/Morse_code.md
  challenges/ciphers/challenges/reverse-cipher/challenge.json
  challenges/ciphers/challenges/reverse-cipher/docs/1-Cryptography.md
  challenges/ciphers/challenges/reverse-cipher/docs/Reverse.md
  challenges/games/challenges/noughts/challenge.json
  challenges/games/challenges/noughts/docs/Code.md
  challenges/games/challenges/prize/challenge.json
  challenges/games/challenges/prize/docs/Code.md
  challenges/games/challenges/rock-paper-scissors/challenge.json
  challenges/games/challenges/rock-paper-scissors/docs/Code.md
  challenges/games/challenges/seven-up/challenge.json
  challenges/games/challenges/seven-up/docs/Code.md
  challenges/games/challenges/yahtzee/challenge.json
  challenges/games/challenges/yahtzee/docs/Code.md
  ui/src/pages/error-pages/preLoginPage.jsx
Labels: 2 story pt

#205 Separate cipher challenge images.
  Makefile
  challenges/ciphers/challenges/caesar-cipher/template.yaml
  challenges/ciphers/challenges/comprehensive-challenge/template.yaml
  challenges/ciphers/challenges/letter-to-number/template.yaml
  challenges/ciphers/challenges/morse-code/template.yaml
  challenges/ciphers/challenges/reverse-cipher/template.yaml
  images/challenges/ciphers/caesar/Dockerfile
  images/challenges/ciphers/comprehensive/Dockerfile
  images/challenges/ciphers/letter-number/Dockerfile
  images/challenges/ciphers/morse/Dockerfile
  images/challenges/ciphers/reverse/Dockerfile
  images/penimage/Dockerfile
Labels: 1 story pt

#209 Sprint7 edit cipher challenges
  challenges/ciphers/challenges/caesar-cipher/challenge.json
  challenges/ciphers/challenges/caesar-cipher/code/Caesar-cipher.py
  challenges/ciphers/challenges/comprehensive-challenge/challenge.json
  challenges/ciphers/challenges/comprehensive-challenge/code/Comprehensive-Challenge.py
  challenges/ciphers/challenges/letter-to-number/challenge.json
  challenges/ciphers/challenges/letter-to-number/code/Letter-to-Number.py
  challenges/ciphers/challenges/morse-code/challenge.json
  challenges/ciphers/challenges/morse-code/code/Morse_code.py
  challenges/ciphers/challenges/reverse-cipher/challenge.json
  challenges/ciphers/challenges/reverse-cipher/code/Reverse.py
Labels: 2 story pt
