Repository acasi-ctf/ctf, pull requests merged in 2021-09, with the labels that each got.

#92 Dynamic UI
  ui/src/components/FlagTurnIn.jsx
  ui/src/dynamic_pages/App.css
  ui/src/dynamic_pages/App.js
  ui/src/dynamic_pages/Components/ChallengeCard.jsx
  ui/src/dynamic_pages/Pages/ChallengePage.jsx
  ui/src/dynamic_pages/Pages/ChallengeSets.jsx
  ui/src/dynamic_pages/Pages/ChallengeSetsNotFound.jsx
  ui/src/dynamic_pages/Services/ErrorBoundary.jsx
  ui/src/dynamic_pages/Services/useFetch.js
  ui/src/pages/ReverseCipher.js
Labels: Medium

#115 Kali tools
  .github/workflows/super-linter.yaml
  Makefile
  challenges/kali/DockerNotes.md
  challenges/kali/Intro/DockerFile.txt
  challenges/kali/Intro/lock.cpp
Labels: challenges

#123 cc UI file reorg.
  ui/src/App.js
  ui/src/components/SubMenu.js
  ui/src/components/Terminal.tsx
  ui/src/pages/DirectoryTraversal.js
  ui/src/pages/Home.js
  ui/src/pages/LeaderBoard.js
  ui/src/pages/Selection.js
  ui/src/pages/challenge-data/ChallengeSet1Data.js
  ui/src/pages/challenge-data/ComprehensiveChallengeData.js
  ui/src/pages/challenge-data/DirectoryTraversalData.js
  ui/src/pages/challenge-data/LetterToNumberData.js
  ui/src/pages/challenge-data/MorseCodeData.js
  ui/src/pages/challenge-data/ReverseCipherData.js
  ui/src/pages/challenge-data/WebStructureData.js
  ui/src/pages/challenge-pages/CaeserCipher.js
  ui/src/pages/challenge-pages/ComprehensiveChallenge.js
  ui/src/pages/challenge-pages/EnvironmentPage.js
  ui/src/pages/challenge-pages/LetterToNumber.js
  ui/src/pages/challenge-pages/MorseCode.js
  ui/src/pages/challenge-pages/ReverseCipher.js
  ui/src/pages/challenge-pages/WebStructure.js
  ui/src/style/App.css
  ui/src/style/ChallengeSet1.css
  ui/src/style/Home.css
  ui/src/style/LeaderBoard.css
  ui/src/style/Selection.css
  ui/src/style/SubMenu.css
  ui/src/style/Terminal.css
Labels: UI

#116 Sprint 4 documentation
  README.md
  sprint-reports/Sprint 4.md
  sprint-reports/semester1_retros/Sprint1_RetroSummary.md
  sprint-reports/semester1_retros/Sprint2_RetroSummary.md
  sprint-reports/semester1_retros/Sprint3_RetroSummary.md
Labels: documentation
